root = "."
tmp_dir = "tmp"
[build]
cmd = "go build -o ./tmp/main ./."
full_bin = "PORT=8080 SERVER_URL=localhost:3000 ./tmp/main"
delay = 200
exclude_dir = ["_build", "assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "templ", "html", "js", "django"]
exclude_regex = ["_test\\.go", "_templ\\.go"]
