root = "."
tmp_dir = "tmp"
[build]
cmd = "go build -o ./tmp/sapp ./cmd/sapp"
full_bin = "DATABASE_PATH=./thing.db PORT=3000 ./tmp/sapp"
delay = 200
exclude_dir = ["_build", "assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "templ", "html", "django"]
exclude_regex = ["_test\\.go", "_templ\\.go"]
