package spendings

import (
	"database/sql"
	"encoding/json"
	"log/slog"
	"net/http"
	"time"

	"errors"
	"strconv"

	"git.sr.ht/~relay/sapp-backend/auth"
)

// EditableSharingStatus defines the possible states the frontend can send for updates.
type EditableSharingStatus string

const (
	StatusAlone         EditableSharingStatus = "Alone"
	StatusShared        EditableSharingStatus = "Shared"
	StatusPaidByPartner EditableSharingStatus = "Paid by Partner"
)

// UpdateSpendingPayload defines the structure for the update request body.
// Amount is excluded for now to maintain AI job total consistency.
type UpdateSpendingPayload struct {
	Description  string                `json:"description"`
	CategoryName string                `json:"category_name"`
	SharingStatus EditableSharingStatus `json:"sharing_status"`
}


// SpendingItem represents a single item within a transaction group (often generated by AI).
type SpendingItem struct {
	ID                 int64   `json:"id"` // spending.id
	Amount             float64 `json:"amount"`
	Description        string  `json:"description"`
	CategoryName       string  `json:"category_name"`
	BuyerName          string  `json:"buyer_name"`           // Name of the user who paid for the original transaction
	PartnerName        *string `json:"partner_name"`         // Name of the partner involved, if any
	SharedUserTakesAll bool    `json:"shared_user_takes_all"` // True if partner pays this item's full cost
	SharingStatus      string  `json:"sharing_status"`       // Derived: "Alone", "Shared with X", "Paid by X"
}

// TransactionGroup represents a single purchase/submission, potentially containing multiple spending items.
type TransactionGroup struct {
	JobID               int64          `json:"job_id"` // ai_categorization_jobs.id
	Prompt              string         `json:"prompt"`
	TotalAmount         float64        `json:"total_amount"`
	JobCreatedAt        time.Time      `json:"job_created_at"`
	BuyerName           string         `json:"buyer_name"` // Added: Name of the user who submitted the job
	IsAmbiguityFlagged  bool           `json:"is_ambiguity_flagged"`
	AmbiguityFlagReason *string        `json:"ambiguity_flag_reason"` // Pointer to handle NULL/empty
	Spendings           []SpendingItem `json:"spendings"`
}

// HandleGetSpendings returns an http.HandlerFunc that fetches spendings grouped by AI job for the logged-in user.
// TODO: Add handling for manual spendings not linked to an AI job.
func HandleGetSpendings(db *sql.DB) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		userID, ok := auth.GetUserIDFromContext(r.Context())
		if !ok {
			slog.Error("failed to get user ID from context for getting spendings", "url", r.URL)
			http.Error(w, "Authentication error", http.StatusInternalServerError)
			return
		}

		// 1. Fetch AI Categorization Jobs initiated by the user, joining users table for buyer name
		jobQuery := `
			SELECT
				j.id, j.prompt, j.total_amount, j.created_at, j.is_ambiguity_flagged, j.ambiguity_flag_reason, u.first_name AS buyer_name
			FROM ai_categorization_jobs j
			JOIN users u ON j.buyer = u.id
			WHERE j.buyer = ?
			ORDER BY j.created_at DESC;
		`
		jobRows, err := db.Query(jobQuery, userID)
		if err != nil {
			slog.Error("failed to query AI categorization jobs", "url", r.URL, "user_id", userID, "err", err)
			http.Error(w, "Internal server error", http.StatusInternalServerError)
			return
		}
		defer jobRows.Close() // Keep the defer for safety

		transactionGroups := []TransactionGroup{}

		// Define query string outside loop
		spendingQuery := `
			SELECT
				s.id,
				s.amount,
				s.description,
				c.name AS category_name,
				u_buyer.first_name AS buyer_name,
				u_partner.first_name AS partner_name,
				us.shared_user_takes_all,
				us.shared_with -- Include shared_with ID to determine sharing status
			FROM spendings s
			JOIN ai_categorized_spendings acs ON s.id = acs.spending_id
			JOIN user_spendings us ON s.id = us.spending_id
			JOIN categories c ON s.category = c.id
			JOIN users u_buyer ON us.buyer = u_buyer.id -- Buyer of the specific spending (should match job buyer)
			LEFT JOIN users u_partner ON us.shared_with = u_partner.id
			WHERE acs.job_id = ?
			ORDER BY s.id ASC; -- Order spendings within a job consistently
		`
		spendingStmt, err := db.Prepare(spendingQuery)
		if err != nil {
			slog.Error("failed to prepare spending query statement", "url", r.URL, "user_id", userID, "err", err)
			http.Error(w, "Internal server error", http.StatusInternalServerError)
			return
		}
		defer spendingStmt.Close()

		// 2. Iterate through jobs and fetch associated spendings
		for jobRows.Next() {
			var group TransactionGroup
			var ambiguityReason sql.NullString // Use sql.NullString for nullable reason

			if err := jobRows.Scan(
				&group.JobID,
				&group.Prompt,
				&group.TotalAmount,
				&group.JobCreatedAt,
				&group.IsAmbiguityFlagged,
				&ambiguityReason,
				&group.BuyerName, // Scan the buyer's name
			); err != nil {
				slog.Error("failed to scan AI job row", "url", r.URL, "user_id", userID, "err", err)
				// Log and continue to next job? Or fail request? Let's fail for now.
				http.Error(w, "Internal server error", http.StatusInternalServerError)
				return
			}

			if ambiguityReason.Valid {
				group.AmbiguityFlagReason = &ambiguityReason.String
			} else {
				group.AmbiguityFlagReason = nil
			}

			// Fetch spendings for this job ID
			spendingRows, err := spendingStmt.Query(group.JobID)
			if err != nil {
				slog.Error("failed to query spendings for job", "url", r.URL, "user_id", userID, "job_id", group.JobID, "err", err)
				http.Error(w, "Internal server error", http.StatusInternalServerError)
				return
			}
			// Ensure spendingRows is closed after the inner loop finishes
			// Do NOT defer here, as it's inside the outer jobRows loop.
			// defer spendingRows.Close() // Close rows associated with this specific job <-- REMOVED DEFER

			group.Spendings = []SpendingItem{} // Initialize slice
			for spendingRows.Next() {
				var item SpendingItem
				var partnerName sql.NullString
				var sharedWithID sql.NullInt64

				if err := spendingRows.Scan(
					&item.ID,
					&item.Amount,
					&item.Description,
					&item.CategoryName,
					&item.BuyerName, // This should be the same as the job buyer, but we fetch it per spending item
					&partnerName,
					&item.SharedUserTakesAll,
					&sharedWithID,
				); err != nil {
					slog.Error("failed to scan spending item row", "url", r.URL, "user_id", userID, "job_id", group.JobID, "err", err)
					spendingRows.Close() // Close inner rows before returning
					http.Error(w, "Internal server error", http.StatusInternalServerError)
					return
				}

				// Set partner name
				if partnerName.Valid {
					item.PartnerName = &partnerName.String
				} else {
					item.PartnerName = nil
				}

				// Determine Sharing Status for the item
				if !sharedWithID.Valid {
					item.SharingStatus = "Alone"
				} else if item.SharedUserTakesAll {
					if item.PartnerName != nil {
						item.SharingStatus = "Paid by " + *item.PartnerName
					} else {
						item.SharingStatus = "Paid by Partner"
					}
				} else {
					if item.PartnerName != nil {
						item.SharingStatus = "Shared with " + *item.PartnerName
					} else {
						item.SharingStatus = "Shared"
					}
				}
				group.Spendings = append(group.Spendings, item)
			}
			spendingRows.Close() // Explicitly close rows after iterating

			// Check for errors during spending iteration
			if err := spendingRows.Err(); err != nil { // spendingRows.Err() checks for errors after the loop
				slog.Error("error iterating spending item rows", "url", r.URL, "user_id", userID, "job_id", group.JobID, "err", err)
				http.Error(w, "Internal server error", http.StatusInternalServerError)
				return
			}

			transactionGroups = append(transactionGroups, group)
		} // End of jobRows loop

		// Check for errors from iterating over job rows.
		if err := jobRows.Err(); err != nil {
			slog.Error("error iterating AI job rows", "url", r.URL, "user_id", userID, "err", err)
			http.Error(w, "Internal server error", http.StatusInternalServerError)
			return
		}

		// TODO: Query and append manual spendings separately if needed

		w.Header().Set("Content-Type", "application/json")
		if err := json.NewEncoder(w).Encode(transactionGroups); err != nil {
			slog.Error("failed to encode transaction groups to JSON", "url", r.URL, "user_id", userID, "err", err)
			// Avoid writing header again if already written
		}
	}
}


// HandleUpdateSpending allows updating the description, category, and sharing status of a specific spending item.
func HandleUpdateSpending(db *sql.DB) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		userID, ok := auth.GetUserIDFromContext(r.Context())
		if !ok {
			slog.Error("failed to get user ID from context for updating spending", "url", r.URL)
			http.Error(w, "Authentication error", http.StatusInternalServerError)
			return
		}

		// 1. Get Spending ID from path
		spendingIDStr := r.PathValue("spending_id")
		spendingID, err := strconv.ParseInt(spendingIDStr, 10, 64)
		if err != nil {
			slog.Warn("invalid spending ID format", "url", r.URL, "user_id", userID, "spending_id_str", spendingIDStr, "err", err)
			http.Error(w, "Invalid spending ID", http.StatusBadRequest)
			return
		}

		// 2. Decode Payload
		var payload UpdateSpendingPayload
		if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
			slog.Error("failed to decode update spending request body", "url", r.URL, "user_id", userID, "spending_id", spendingID, "err", err)
			http.Error(w, "Bad Request: Invalid JSON", http.StatusBadRequest)
			return
		}
		defer r.Body.Close()

		// 3. Validate Payload
		if payload.CategoryName == "" {
			slog.Warn("invalid update spending payload: missing category", "url", r.URL, "user_id", userID, "spending_id", spendingID, "payload", payload)
			http.Error(w, "Bad Request: Category name is required", http.StatusBadRequest)
			return
		}
		isValidStatus := false
		validStatuses := []EditableSharingStatus{StatusAlone, StatusShared, StatusPaidByPartner}
		for _, s := range validStatuses {
			if payload.SharingStatus == s {
				isValidStatus = true
				break
			}
		}
		if !isValidStatus {
			slog.Warn("invalid update spending payload: invalid sharing status", "url", r.URL, "user_id", userID, "spending_id", spendingID, "payload", payload)
			http.Error(w, "Bad Request: Invalid sharing status", http.StatusBadRequest)
			return
		}

		// 4. Begin Transaction
		tx, err := db.Begin()
		if err != nil {
			slog.Error("failed to begin transaction for update spending", "url", r.URL, "user_id", userID, "spending_id", spendingID, "err", err)
			http.Error(w, "Internal server error", http.StatusInternalServerError)
			return
		}
		defer tx.Rollback() // Rollback on error

		// 5. Verify Authorization: Check if the user is the buyer of this spending item
		var buyerID int64
		err = tx.QueryRow("SELECT buyer FROM user_spendings WHERE spending_id = ?", spendingID).Scan(&buyerID)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				slog.Warn("update spending attempt on non-existent spending or user_spending link", "url", r.URL, "user_id", userID, "spending_id", spendingID)
				http.Error(w, "Spending item not found", http.StatusNotFound)
			} else {
				slog.Error("failed to query buyer for spending item", "url", r.URL, "user_id", userID, "spending_id", spendingID, "err", err)
				http.Error(w, "Internal server error", http.StatusInternalServerError)
			}
			return
		}
		if buyerID != userID {
			slog.Warn("unauthorized attempt to update spending item", "url", r.URL, "user_id", userID, "spending_id", spendingID, "actual_buyer_id", buyerID)
			http.Error(w, "Forbidden: You can only edit your own spending items", http.StatusForbidden)
			return
		}

		// 6. Get Category ID
		var categoryID int64
		err = tx.QueryRow("SELECT id FROM categories WHERE name = ?", payload.CategoryName).Scan(&categoryID)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				slog.Warn("category not found during update spending", "url", r.URL, "user_id", userID, "spending_id", spendingID, "category_name", payload.CategoryName)
				http.Error(w, "Category not found", http.StatusBadRequest) // Bad request because category name is invalid
			} else {
				slog.Error("failed to query category ID during update spending", "url", r.URL, "user_id", userID, "spending_id", spendingID, "err", err)
				http.Error(w, "Internal server error", http.StatusInternalServerError)
			}
			return
		}

		// 7. Determine new user_spendings values based on SharingStatus
		var sharedWithID *int64 = nil
		var sharedUserTakesAll bool = false
		var partnerID int64
		partnerExists := false

		if payload.SharingStatus == StatusShared || payload.SharingStatus == StatusPaidByPartner {
			// Need partner ID for these statuses
			fetchedPartnerID, ok := auth.GetPartnerUserID(userID)
			if !ok {
				// Check if the status requires a partner
				if payload.SharingStatus == StatusShared || payload.SharingStatus == StatusPaidByPartner {
					slog.Warn("attempted to set sharing status requiring partner, but no partner configured", "url", r.URL, "user_id", userID, "spending_id", spendingID, "status", payload.SharingStatus)
					http.Error(w, "Cannot set status to 'Shared' or 'Paid by Partner': No partner configured for your user.", http.StatusBadRequest)
					return
				}
				// If status is 'Alone', it's fine that no partner exists.
			} else {
				partnerID = fetchedPartnerID
				partnerExists = true // Assume partner exists if GetPartnerUserID returns one
				// Optional: Verify partner exists in DB? For simplicity, we trust GetPartnerUserID for now.
			}

			if partnerExists {
				sharedWithID = &partnerID
				if payload.SharingStatus == StatusPaidByPartner {
					sharedUserTakesAll = true
				}
			}
		}
		// If payload.SharingStatus is StatusAlone, sharedWithID remains nil and sharedUserTakesAll remains false.

		// 8. Update spendings table
		_, err = tx.Exec(`UPDATE spendings SET description = ?, category = ? WHERE id = ?`,
			payload.Description, categoryID, spendingID)
		if err != nil {
			// Check if the spending item itself was deleted between checks (unlikely but possible)
			// Or if there's another DB error.
			slog.Error("failed to update spendings table", "url", r.URL, "user_id", userID, "spending_id", spendingID, "err", err)
			http.Error(w, "Internal server error", http.StatusInternalServerError)
			return
		}

		// 9. Update user_spendings table
		_, err = tx.Exec(`UPDATE user_spendings SET shared_with = ?, shared_user_takes_all = ? WHERE spending_id = ?`,
			sharedWithID, sharedUserTakesAll, spendingID)
		if err != nil {
			// This update should always find a row because we checked user_spendings in step 5.
			slog.Error("failed to update user_spendings table", "url", r.URL, "user_id", userID, "spending_id", spendingID, "err", err)
			http.Error(w, "Internal server error", http.StatusInternalServerError)
			return
		}

		// 10. Commit Transaction
		if err = tx.Commit(); err != nil {
			slog.Error("failed to commit transaction for update spending", "url", r.URL, "user_id", userID, "spending_id", spendingID, "err", err)
			http.Error(w, "Internal server error", http.StatusInternalServerError)
			return
		}

		slog.Info("Spending item updated successfully", "url", r.URL, "user_id", userID, "spending_id", spendingID)
		w.WriteHeader(http.StatusOK) // Send 200 OK on success
	}
}
